### ISSUE TITLE
Issue with switch from strftime() to date()

### ISSUE THREAD

**Issue by bbouchard-seedbox** [middlewares/access-log#23]
https://github.com/middlewares/access-log/blob/205cfd7d47c3523c60624815244851fa0a97ed1f/src/AccessLog.php#L182

It seems like the default value for getRequestTime() isn't compatible with the changes. Default format should use date() format rather than strftime()

example:
Before -> [17/May/2022:10:51:10 -0600]
After change -> [%17/%b/%2022:%10:%May:%th %136]

**Comment by oscarotero** [comment]
Fixed in v2.1.2. thanks!
