### ISSUE TITLE
[RFC] Read IP from request attribute

### ISSUE THREAD

**Issue by ajgarlag** [middlewares/access-log#6]
Detecting client IP is a tricky business, so the need for a middleware like https://github.com/middlewares/client-ip/

What do you think about adding an option to read IP parameter from a request attribute?

**Comment by oscarotero** [comment]
Good idea.
In fact, there's the same feature in [middlewares/firewall](https://github.com/middlewares/firewall#ipattributestring-ipattribute) that we can replicate.

**Comment by ajgarlag** [comment]
To replicate it, `AccessLog::commonFormat` cannot be static. I'll remove `static` keyword from all methods. What do you think?

**Comment by oscarotero** [comment]
Yes, no problem. 👍
